name: "Send Price To Telegram"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/10 * * * *'  # Run every 15 minutes
env: 
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version (update if needed)

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Execute Python Script
        run: python main.py

      - name: Configure Git
        run: |
          git config --global user.email "me@xigma.com"
          git config --global user.name "xigmaDev"

      - name: Commit changes
        run: |
          git add -A
          git diff --cached --quiet || git commit -m "Automatic update - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M')"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}