name: "Send Price To Telegram"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
env: 
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version (update if needed)

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Execute Python Script
        run: python tgju.py
